- name: Install MySQL, PostgreSQL, and NGINX
  hosts: localhost
  become: yes
  connection: local

  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Install MySQL
      apt:
        name: mysql-server
        state: present

    - name: Configure MySQL to listen on all interfaces
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: "^bind-address"
        line: "bind-address = 0.0.0.0"

    - name: Restart MySQL
      service:
        name: mysql
        state: restarted

    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present

    - name: Set PostgreSQL to listen on all addresses
      lineinfile:
        path: /etc/postgresql/*/main/postgresql.conf
        regexp: "^#?listen_addresses"
        line: "listen_addresses = '*'"

    - name: Allow external connections to PostgreSQL
      blockinfile:
        path: /etc/postgresql/*/main/pg_hba.conf
        block: |
          host    all             all             0.0.0.0/0               md5

    - name: Restart PostgreSQL
      service:
        name: postgresql
        state: restarted

    - name: Install NGINX
      apt:
        name: nginx
        state: present

    - name: Start and enable NGINX
      service:
        name: nginx
        state: started
        enabled: yes
