---
postgresql_package: postgresql
postgresql_version: "14"
postgresql_conf_path: "/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf"
postgresql_hba_path: "/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf"
